# site properties and page defaults
title: The Embodied Neural Computation and Awareness Lab
subtitle: at the University of Montana
description: Most cognitive neuroscience research, especially concerning humans, treats the brain as if it were a standalone computer. In reality, neural "computation" both influences and is itself modulated by biological processes elsewhere in the body. We study how the brain-body axis shapes our conscious experiences of the world and of ourselves. To this end, we integrate computational and empirical approaches to concretely link biological mechanisms with downstream psychological manifestations, leveraging a variety of behavioral (e.g., perceptual psychophyics) and non-invasive physiological (e.g., electroencephalography/EEG, cardiography, blood pressure) measures and interventions (e.g., electrical muscle stimulation, galvanic vestibular stimulation). Our lab space is located in the basement of the Skaggs Research Building, where we host a state-of-the-art EEG facility.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: john.veillette@umontana.edu
  orcid: 0000-0002-0332-4372
  google-scholar: V56wBKMAAAAJ
  github: embodied-neuro

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
