- id: doi:10.7554/eLife.95599.2
  title: Cardiac afferent signals can facilitate visual dominance in binocular rivalry
  type: paper
  image: https://iiif.elifesciences.org/lax:95599%2Felife-95599-fig1-v1.tif/full/1500,/0/default.jpg

- id: doi:10.1038/s44271-025-00323-5
  title: Intentional binding effect depends on conscious access to the sensory consequences of action
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs44271-025-00323-5/MediaObjects/44271_2025_323_Fig2_HTML.png?as=webp

- id: doi:10.1523/JNEUROSCI.1673-24.2025
  title: Overlapping Cortical Substrate of Biomechanical Control and Subjective Agency
  type: paper
  image: https://www.jneurosci.org/content/jneuro/45/18/e1673242025/F3.large.jpg
