- id: doi:10.7554/eLife.95599.2
  title: Cardiac afferent signals can facilitate visual dominance in binocular rivalry
  type: paper
  image: https://iiif.elifesciences.org/lax:95599%2Felife-95599-fig1-v1.tif/full/1500,/0/default.jpg

- id: doi:10.1038/s44271-025-00323-5
  title: Intentional binding effect depends on conscious access to the sensory consequences of action
  type: paper
  image: assets/figures/binding.png

- id: doi:10.1523/JNEUROSCI.1673-24.2025
  title: Overlapping Cortical Substrate of Biomechanical Control and Subjective Agency
  type: paper
  image: images/share.jpg

- id: doi:10.1523/JNEUROSCI.2294-24.2025
  title: Timing of speech in brain and glottis and the feedback delay problem in motor control
  type: paper
  image: assets/figures/glottis.jpg

- id: doi:10.1523/JNEUROSCI.1116-23.2023
  type: paper
  image: assets/figures/decoder.jpg

- id: doi:10.1016/j.cub.2025.08.007
  type: paper

- id: doi:10.1016/j.concog.2024.103745
  type: paper

- id: doi:10.31234/osf.io/u2erk_v2
  type: preprint

- id: doi:10.1038/s41598-023-41613-4
  type: paper

- id: doi:10.64898/2026.08.17.745255
  type: preprint
  image: assets/figures/streaming.png
